# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'gst_test1' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gst_test1
  pod 'Alamofire', '~> 4.4'

  target 'gst_test1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gst_test1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
